apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: test
          image: alpine
          command: ["sleep", "infinity"] 
      restartPolicy: Never
