apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namespace: test
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: test
        image: harbor.local/dockerhub-cache/library/alpine:3.18
        command: ["sleep", "infinity"] 
        securityContext:
          runAsNonRoot: true
          runAsUser: 1002
          runAsGroup: 1000
      restartPolicy: Never
