apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Test
metadata:
  name: test
spec:
  match:
    kinds:
      - apiGroups: ["batch"]
        kinds: ["Job"]
    namespaceSelector:
      matchLabels:
        label: gatekeeper
